# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kording lab"
title:              "Kording lab at University of Pennsylvania"
description:        "this is a page for Konrad Kording lab, we are comptational neurosciece and datascience lab at the University of Pennsylvania, Philadelphia"


# URL
url:                https://TTI-DEL.github.io/Lab
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/Lab"
  - name:           "about"
    href:           "/Lab/about"
  - name:           "publications"
    href:           "/Lab/publication"
  - name:           "people"
    href:           "/Lab/people"
  - name:           "blog"
    href:           "/Lab/blog"
  - name:           "resources"
    href:           "/Lab/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /Lab/people/:title/index.html
